/* WARNING: Generated by "make-toolchain-version". */

#include <sys/types.h>
#include <libelftc.h>

const char *
elftc_version(void)
{
	return "elftoolchain HEAD Linux git:heads/trunk-0-gf7e9afc6";
}
